### ISSUE TITLE
UTILS not accepted.

### ISSUE THREAD

**Issue by samirelanduk** [j6k4m8/greenblocks#9]
I had a game where the word was UTILS but when I entered UTILS it said it wasn't a valid word.

Thanks for making this by the way!

**Comment by j6k4m8** [comment]
Thank you so much for reporting, I am fixing it now!

Super super glad you're enjoying it :)

**Comment by j6k4m8** [comment]
Just fixed it and it will be automatically re-deployed in a few seconds. So sorry you had that lousy experience!

**Comment by samirelanduk** [comment]
Thanks! Haha, it was a minor blip.
